var routes = {
  "about"                 : "about/about.html;About",
  // "archives"              : "about/archives.html",
  // "developmentroadmap"    : "about/roadmap.html",
  // "news"                  : "about/news.html",
  // "advisoryboard"         : "about/advisoryboard.html",
  // "collections"           : "about/collections.html",
  "support"               : "support/support.html;Support",
  // "faq"                   : "support/faq.html",
  "help"                  : "support/help.html;Help",
  // "librarians"            : "support/librarians.html",
  "sitemap"               : "about/sitemap.html;Site map",
  "termsofuse"            : "about/termsofuse.html;Terms of use",
  "accessibility"         : "about/accessibilityPSBAR.html;Accessibiltiy",
  "cookies"               : "about/cookies.html;Cookies",
  "privacy"               : "about/privacy.html;Privacy",
  // "features"              : "support/features.html",
  "quickref"              : "support/quickref.html;QRG",
  // "witchcraft"            : "features/witchcraft.html",
  // "blcovers"              : "features/blcovers.html",
  // "shakespeare"           : "features/shakespeare.html",
  // "music"                 : "features/music.html",
  "surveys"               : "about/surveys.html;Surveys",
  "wellcome"              : "collections/wellcome.html;Wellcome collection",
  "leeds"                 : "collections/leeds.html;University of Leeds collection",
  "rcse"                  : "collections/rcse.html;RSCE collection",
  "rcpe"                  : "collections/rcpe.html;RCPE collection",
  "glasgow"               : "collections/glasgow.html;University of Glasgow collection",
  "ucl"                   : "collections/ucl.html; UCL collection",
  "rcp"                   : "collections/rcp.html;Royal College of Physicians collection",
  "tropical"              : "collections/tropical.html;Tropical medicine collection",
  "kings"                 : "collections/kings.html;Kings College collection",
  "bristol"               : "collections/bristol.html;University of Bristol collection",
  "info"                  : "more_information.html;Visualisations info"
  };
