var routes = {
  "about"                 : "about/about.html;About",
  "archives"              : "about/archives.html;Archives",
  "news"                  : "about/news.html;News",
  "collections"           : "about/collections.html;Collections",
  "titlelist"             : "about/titlelistburney.html;Title List",
  "browser"               : "about/browser.html;Browser Compatibility",
  "support"               : "support/support.html;Support",
  "faq"                   : "support/faq.html;Frequently Asked Questions",
  "help"                  : "support/help.html;Help File",
  "librarians"            : "support/librarians.html;Librarians",
  "sitemap"               : "about/sitemap.html;Site Map",
  "termsofuse"            : "about/termsofuse.html;Terms of Use",
  "accessibility"         : "about/accessibilityPSBAR.html;Accessibility",
  "privacy"               : "about/privacy.html;Privacy Statement",
  "cookies"               : "about/cookies.html;Cookies",
  "features"              : "support/features.html;Features",
  "quickref"              : "support/quickref.html;Quick Reference Guide",
  "newuser"				  : "support/newuser.html;New User"
};
