var routes = {
  "about"                 : "about/about.html;About",
  "archives"              : "about/archives.html;Archives",
  "developmentroadmap"    : "about/roadmap.html;Development Roadmap",
  "news"                  : "about/news.html;News",
  "advisoryboard"         : "about/advisoryboard.html;Advisory Board",
  "collections"           : "about/collections.html;Collections",
  "support"               : "support/support.html;Support",
  "faq"                   : "support/faq.html;Frequently Asked Questions",
  "help"                  : "support/help.html;Help File",
  "librarians"            : "support/librarians.html;Librarians",
  "sitemap"               : "about/sitemap.html;Site Map",
  "termsofuse"            : "about/termsofuse.html;Terms of Use",
  "accessibility"         : "about/accessibilityPSBAR.html;Accessibility",
  "privacy"               : "about/privacy.html;Privacy Statement",
  "cookies"               : "about/cookies.html;Cookies",
  "features"              : "support/features.html;Features",
  "quickref"              : "support/quickref.html;Quick Reference Guide",
  "witchcraft"            : "features/witchcraft.html;Witchcraft Feature",
  "blcovers"              : "features/blcovers.html;British Library Covers Feature",
  "shakespeare"           : "features/shakespeare.html;Shakespeare Feature",
  "music"                 : "features/music.html;Music Feature",
  "maps"                  : "features/maps.html;Maps Feature",
  "locallondon"           : "features/locallondon.html;London Local History Feature",
  "surveys"               : "about/surveys.html;Surveys",
  "christmas"             : "features/christmas.html;Christmas Feature",
  "travel"                : "features/travel.html;Travel Feature",
  "astronomy"             : "features/astronomy.html;Astronomy Feature",
  "cookery"               : "features/cookery.html;Cookery Feature",
  "presentations"         : "about/presentations.html;Presentations",
  "reports"         	  : "about/reports.html;Reports",
  "events"                : "about/events.html;Events",
  "labs"                  : "about/labs.html;Labs",    
  "stem"                  : "features/stem.html;STEM Feature",
  "comedy"                : "features/comedy.html;Comedy Feature",
  "browser"               : "about/browser.html;Browser Compatibility",
  "opencookery"           : "features/opencookery.html;Open Access Cookery Feature",
  "opentravel"            : "features/opentravel.html;Open Access Travel Feature",
  "openfitness"           : "features/openfitness.html;Open Access Fitness Feature",
  "blackhistory"          : "features/blackhistory.html;Black History Feature",
  "animals"          	  : "features/animals.html;Animals Feature",
  "newuser"				  : "support/newuser.html;New User"
	
};
